# http://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
    - nodejs_version: 0.12
    - nodejs_version: 4
    - nodejs_version: 5

version: "{build}"

build:
  - provider: Environment
    name: production
    on:
      branch: master
      appveyor_repo_tag: true

deploy: off

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm set progress=false
  - npm prune
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test
